cp /mingw64/bin/libgcc_s_seh-1.dll                      .
cp /mingw64/bin/libwinpthread-1.dll                     .
cp /mingw64/bin/libcrypto-3-x64.dll                     .
cp /mingw64/bin/wxmsw32u_html_gcc_custom.dll            .
cp /mingw64/bin/wxbase32u_gcc_custom.dll                .
cp /mingw64/bin/wxmsw32u_core_gcc_custom.dll            .
cp /mingw64/bin/libstdc++-6.dll                         .
cp /mingw64/bin/wxmsw32u_richtext_gcc_custom.dll        .
cp /mingw64/bin/liblzma-5.dll                           .
cp /mingw64/bin/libpcre2-16-0.dll                       .
cp /mingw64/bin/zlib1.dll                               .
cp /mingw64/bin/libjpeg-8.dll                           .
cp /mingw64/bin/libpng16-16.dll                         .
cp /mingw64/bin/libtiff-6.dll                           .
cp /mingw64/bin/wxbase32u_xml_gcc_custom.dll            .
cp /mingw64/bin/libLerc.dll                             .
cp /mingw64/bin/libjbig-0.dll                           .
cp /mingw64/bin/libdeflate.dll                          .
cp /mingw64/bin/libwebp-7.dll                           .
cp /mingw64/bin/libzstd.dll                             .
cp /mingw64/bin/libexpat-1.dll                          .
cp /mingw64/bin/libsharpyuv-0.dll                       .